# Generated by Django 3.2.13 on 2022-06-15 23:49

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pasttoollisting",
            name="image",
            field=models.ImageField(
                upload_to=base.models.file_path, verbose_name="listing image"
            ),
        ),
        migrations.AlterField(
            model_name="toollisting",
            name="image",
            field=models.ImageField(
                upload_to=base.models.file_path, verbose_name="listing image"
            ),
        ),
    ]
