# Generated by Django 3.2.13 on 2022-05-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasttoollisting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='toollisting',
            name='image',
        ),
    ]
